---
- name: Checking if composer is installed.
  stat: path=/usr/local/bin/composer
  register: composer_folder

- name: Composer install - Downloading
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  when: not composer_folder.stat.exists

- name: Composer install - Configuring path
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  when: not composer_folder.stat.exists

- name: Composer install - Making executable
  shell: chmod a+x /usr/local/bin/composer
  when: not composer_folder.stat.exists

- name: Checking if drush is installed.
  stat: path=/usr/share/php/drush
  register: drush_folder

- name: Drush install - Add pear-channel
  shell: pear channel-discover pear.drush.org || true
  when: not drush_folder.stat.exists

- name: Drush install - Installing drush
  shell: pear install -f drush/drush
  when: not drush_folder.stat.exists

- name: Checking if Drush dependancy Console table is installed.
  stat: path=/usr/share/php/drush/lib/Console_Table-1.1.3
  register: drush_console_table_folder

- name: Drush install - Downloading dependency Console table
  get_url: url=http://download.pear.php.net/package/Console_Table-1.1.3.tgz dest=/usr/share/php/drush/lib
  when: not drush_console_table_folder.stat.exists

- name: Drush install - Extracting dependency Console table
  unarchive: src=/usr/share/php/drush/lib/Console_Table-1.1.3.tgz dest=/usr/share/php/drush/lib copy=no
  when: not drush_console_table_folder.stat.exists

- name: Drush install - Removing dependency Console table tgz-file.
  file: path=/usr/share/php/drush/lib/Console_Table-1.1.3.tgz state=absent
  when: not drush_console_table_folder.stat.exists